version: "3"
services:
  rabbitmq:
    image: "rabbitmq:alpine"
    environment:
      RABBITMQ_DEFAULT_USER: robot
      RABBITMQ_DEFAULT_PASS: HQia9PUlAk
    restart: always
    ports:
      - "5672:5672"
  robot:
    build:
      context: ./robot/
      dockerfile: Dockerfile-robot
    environment:
      RABBITMQ_DEFAULT_USER: robot
      RABBITMQ_DEFAULT_PASS: HQia9PUlAk
  camera:
    build:
      context: ./robot/
      dockerfile: Dockerfile-camera
    environment:
      RABBITMQ_DEFAULT_USER: robot
      RABBITMQ_DEFAULT_PASS: HQia9PUlAk
  motors:
    build:
      context: ./robot/
      dockerfile: Dockerfile-motors
    environment:
      RABBITMQ_DEFAULT_USER: robot
      RABBITMQ_DEFAULT_PASS: HQia9PUlAk

