FROM python:3.10.0a1-slim

RUN apt update && \
    apt install -y gcc && python3-opencv

RUN mkdir /app
COPY src/ /app/

RUN pip install -r /app/requirements.txt

ENTRYPOINT ["python", "/app/camera.py"]
